title: A11yhood site Settings
description: >- # this means to ignore newlines until "baseurl:"
  a consistent theme for the a11yhood project
baseurl: "site-settings" # the subpath of your site, e.g. /blog
url: "https://a11yhood.org/site-settings" # the base hostname & protocol for your site, e.g. http://example.com