baseurl: site-settings
description: a consistent theme for the a11yhood project
email: caos@googlegroups.com
github_username: a11yhood
plugins:
- jekyll-feed
- jekyll-octicons
- jekyll-readme-index
readme_index:
  enabled: true
  with_frontmatter: true
theme: minima
title: A11yhood site Settings
url: https://a11yhood.org/site-settings
